#!/usr/bin/env bash
# vim: set ft=ruby:

exec /usr/bin/env ruby -x "$0" $*
#!ruby

require "chronic"
require "terminal-table"
require "timezone"

if __FILE__ == $0
  raw_time = ARGV.join(" ")
  time = Chronic.parse(raw_time) || Time.now

  zones = [
    "Australia/Sydney",
    "America/Los_Angeles",
    "America/New_York",
    "Europe/Berlin",
    "Europe/London",
  ].freeze

  valid_timezones = zones.map do |name|
    Timezone[name]
  end.compact.sort

  title = "Local time: #{time}"
  table = Terminal::Table.new(title: title) do |t|
    valid_timezones.each do |zone|
      dst = zone.dst?(time) ? "DST" : ""
      t.add_row [zone.name, dst, zone.time_with_offset(time)]
    end
  end

  puts table
end
